apiVersion: v1
kind: ServiceAccount
metadata:
  name: shlink-redirector
  namespace: shlink
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-shlink-redirector
  namespace: shlink
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: shlink-redirector
          serviceAccountRef:
            name: shlink-redirector
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink-redirector-secrets
  namespace: shlink
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-shlink-redirector
    kind: SecretStore
  target:
    name: shlink-redirector-secrets
  data:
    - secretKey: SHLINK_API_KEY
      remoteRef: { key: shlink, property: api-key }
