apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
  namespace: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: db_url
    remoteRef:
      key: pg-credentials
      property: url
  - secretKey: db_username
    remoteRef:
      key: pg-credentials
      property: username
  - secretKey: db_password
    remoteRef:
      key: pg-credentials
      property: password
