apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
  namespace: backstage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-credentials
    creationPolicy: Owner
    template:
      data:
        credentials: |
          db_con="{{ .db_url }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"
  data:
  - secretKey: db_url
    remoteRef:
      key: kv/data/pg-credentials
      property: url
  - secretKey: db_username
    remoteRef:
      key: kv/data/pg-credentials
      property: username
  - secretKey: db_password
    remoteRef:
      key: kv/data/pg-credentials
      property: password
