# Use the base image from GitHub Container Registry
FROM ghcr.io/christopherscot/go-server-template:main

# Set the working directory
WORKDIR /app

# Expose the port that the application listens on
EXPOSE 3000

# Command to run the application
CMD ["./app"]

# docker run -d -p 3000:3000 go-server-template:latest