apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test-service
    team: fake-team
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 92929
  selector:
    app: test-service
    someotherThing: value
