apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test-service
    team: fake-team
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32767
  selector:
    app: test-service
    someotherThing: value
