apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test-service
    team: fake-team
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: test-service
    someotherThing: value
