apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-clusters
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: cloudnative-pg-clusters
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
