apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dead-mans-switch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
    path: dead-mans-switch
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dead-mans-switch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
