apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontdoor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
    path: frontdoor
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
