apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: LGTM
    repoURL: 'https://github.com/ChristopherScot/homelab.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
