apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    path: lgtm
    repoURL: https://github.com/ChristopherScot/homelab
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  sources: []
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
  finalizers:
  - resources-finalizer.argocd.argoproj.io
