apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://github.com/ChristopherScot/homelab.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 3.3.0
    helm:
      values: |+
      singleBinary:
        replicas: 1
      deploymentMode: SingleBinary
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
          grpc_listen_port: 9095
          log_level: warn
          storage_driver: filesystem
      minio: 
        enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h # 28 days retention
      compactor:
        retention_enabled: true
        delete_request_store: filesystem
      backend:
        replicas: 0
      read:
        replicas: 0
      write:
        replicas: 0

      ingester:
        replicas: 0
      querier:
        replicas: 0
      queryFrontend:
        replicas: 0
      queryScheduler:
        replicas: 0
      distributor:
        replicas: 0
      compactor:
        replicas: 0
      indexGateway:
        replicas: 0
      bloomCompactor:
        replicas: 0
      bloomGateway:
        replicas: 0

      persistence:
        enabled: true
        storageClassName: longhorn
        accessModes:
        - ReadWriteOnce
        size: 50Gi
        numberOfReplicas: 2
          
      # valueFiles:
      # - "$values/loki/values.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
