apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://github.com/ChristopherScot/homelab.git
    path: loki
    ref: values
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 3.3.0
    helm:
      valueFiles:
      - $values/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
