apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 8.0.10 # Replace with the desired version
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
