apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-frontdoor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
    path: nginx-frontdoor
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true