# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx-ingress
#   namespace: ingress-nginx
# spec:
#   project: default
#   source:
#     repoURL: https://kubernetes.github.io/ingress-nginx
#     targetRevision: "4.0.6"  # Specify the desired version
#     chart: ingress-nginx
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: ingress-nginx
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true