# This links to services/deployments etc in my own repo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
    path: nginx-test-2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true