# This links to services/deployments etc in my own repo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ChristopherScot/homelab
    targetRevision: HEAD
    path: nginx-test-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true