apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service
  namespace: argocd
  labels:
    team: fake-team
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChristopherScot/homelab'
    targetRevision: HEAD
    path: test-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
