apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault # Change if "argocd" is not intentional
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-helm
    targetRevision: 0.29.1
    helm:
      valuesObject:
        global:
          enabled: true
          tlsDisable: false # Set to true if TLS is not configured
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
        ui:
          enabled: true
          serviceType: "LoadBalancer"
          externalPort: 8200
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
  - ApplyOutOfSyncOnly=true
  - ServerSideApply=true
