apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
  namespace: backstage
spec:
  backendType: vault
  vault:
    path: secret/data/my-db-credentials
  target:
    name: pg-credentials
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
