apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
  namespace: backstage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-credentials
  data:
  - secretKey: username
    remoteRef:
      key: username
  - secretKey: password
    remoteRef:
      key: /v1/kv/data/pg-credentials
