apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
  namespace: backstage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-credentials
  data:
    - secretKey: username
      remoteRef:
        key: pg-credentials      
        property: username        
    - secretKey: password
      remoteRef:
        key: pg-credentials
        property: password
