apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-password
              key: WEBPASSWORD
        - name: DNS1
          value: "8.8.8.8"
        - name: DNS2
          value: "8.8.4.4"
        ports:
        - containerPort: 80
        - containerPort: 53
        volumeMounts:
        - name: pihole-storage
          mountPath: /etc/pihole
      volumes:
      - name: pihole-storage
        persistentVolumeClaim:
          claimName: pihole-pvc-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-nfs-pv
spec:
  mountOptions:
  - vers=3
  - hard
  - intr
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 192.168.50.220
    path: /volume1/k8s-pv/pihole
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: pihole-nfs-pv
