apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-redirect
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-redirect
  template:
    metadata:
      labels:
        app: go-redirect
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config
        configMap:
          name: go-redirect-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-redirect
  namespace: pihole
spec:
  selector:
    app: go-redirect
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-shortener-redirect
  namespace: pihole
spec:
  ingressClassName: external
  rules:
  - host: go
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: go-redirect
            port:
              number: 80
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: go-redirect-nginx-config
  namespace: pihole
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        return 301 http://go-shortener-redirects.s3-website-us-east-1.amazonaws.com/go$request_uri;
      }
    }
