apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  - port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: pihole
