apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-keys
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-authelia
    kind: SecretStore
  target:
    name: authelia-keys
  data:
    - secretKey: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
      remoteRef:
        key: authelia/keys
        property: jwt_secret
    - secretKey: AUTHELIA_SESSION_SECRET
      remoteRef:
        key: authelia/keys
        property: session_secret
    - secretKey: AUTHELIA_STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: authelia/keys
        property: storage_encryption
