apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-autocaliweb
  namespace: media
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: autocaliweb
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autocaliweb-smtp
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-autocaliweb
    kind: SecretStore
  target:
    name: autocaliweb-smtp
  data:
    - secretKey: host
      remoteRef:
        key: ses/smtp
        property: host
    - secretKey: port
      remoteRef:
        key: ses/smtp
        property: port
    - secretKey: username
      remoteRef:
        key: ses/smtp
        property: username
    - secretKey: password
      remoteRef:
        key: ses/smtp
        property: password
