apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-arr
  namespace: media
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: arr
          serviceAccountRef:
            name: external-secrets-sa
