apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-jellyfin
  namespace: media
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: jellyfin
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-jellyseerr
  namespace: media
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: jellyseerr
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyfin-admin
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-jellyfin
    kind: SecretStore
  target:
    name: jellyfin-admin
  data:
    - secretKey: username
      remoteRef:
        key: jellyfin/super-admin
        property: username
    - secretKey: password
      remoteRef:
        key: jellyfin/super-admin
        property: password
