apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-webdav
  namespace: media
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: webdav
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webdav-creds
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-webdav
    kind: SecretStore
  target:
    name: webdav-creds
    template:
      type: Opaque
      data:
        WEBDAV_USERNAME: "{{ .username }}"
        WEBDAV_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: webdav/supernote
        property: username
    - secretKey: password
      remoteRef:
        key: webdav/supernote
        property: password
