apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: media
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
