apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/app: "argocd-server"
    gethomepage.dev/href: "https://argo.home.chrisscotmartin.com"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "GitOps controller"
    gethomepage.dev/group: "Cluster"
    gethomepage.dev/icon: "argocd.png"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: external
  tls:
    - hosts:
        - argo.home.chrisscotmartin.com
      secretName: argocd-tls
  rules:
    - host: argo.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
    - host: argo.home.chrisscotmartin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
