apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-vault
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  # syncPolicy:
  #   syncOptions:
  #   - Replace=true
  source:
    path: lgtm
    repoURL: https://github.com/ChristopherScot/homelab.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - vault.yaml
  project: default
