apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-test
  namespace: default
  labels:
    app: go-server-test
    team: me-myself-and-i
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server-test
  template:
    metadata:
      labels:
        app: go-server-test
        team: me-myself-and-i
        someotherThing: value
    spec:
      containers:
        - name: go-server-test
          image: ghcr.io/christopherscot/go-server-template:latest
          ports: 
          - containerPort: 3000