apiVersion: v1
kind: Service
metadata:
  name: go-server-test
  namespace: default
  labels:
    app: go-server-test
    team: me-myself-and-i
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32444
  selector:
    app: go-server-test
    someotherThing: value
