apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-admin
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-qbittorrent
    kind: SecretStore
  target:
    name: qbittorrent-admin
  data:
    - secretKey: username
      remoteRef:
        key: qbittorrent/admin
        property: username
    - secretKey: password
      remoteRef:
        key: qbittorrent/admin
        property: password
