apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool-ipv4
  namespace: metallb-system
spec:
  addresses:
  - 192.168.50.225-192.168.50.255 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - primary-pool-ipv4