apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - approvald.yaml
  - argocd.yaml
  - claude-pods.yaml
  - dead-mans-switch.yaml
  - ddns.yaml
  - extras.yaml
  - media.yaml
  - pg-test.yaml
  - shlink.yaml
