apiVersion: v1
kind: Service
metadata:
  name: nginx-frontdoor
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx-frontdoor
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443