apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shlink-db
  namespace: shlink
spec:
  instances: 2
  monitoring:
    enablePodMonitor: true
  storage:
    size: 2Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  bootstrap:
    initdb:
      database: shlink
      owner: shlink
