apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-db
  namespace: pg-test
spec:
  instances: 1
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi
