apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
spec:
  selector:
    matchLabels:
      app: nginx-test-2
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-test-2
    spec:
      containers:
      - name: nginx-test-2
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html-2
          items:
          - key: index.html
            path: index.html