apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2-lb 
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-test-2
  ports:
  - port: 80
    targetPort: 80
    name: http
