apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-test-2
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 10s }
      - setWeight: 40
      - pause: { duration: 10s }
      - setWeight: 60
      - pause: { duration: 10s }
      - setWeight: 80
      - pause: { duration: 10s }
      - setWeight: 100
  selector:
    matchLabels:
      app: nginx-test-2
  template:
    metadata:
      labels:
        app: nginx-test-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.6
        ports:
        - containerPort: 80
