apiVersion: v1
kind: Service
metadata:
  name: argo-lb
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
     app.kubernetes.io/name: argocd-server
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 443
    targetPort: 8080
    name: https