apiVersion: v1
kind: Service
metadata:
  name: argo-lb
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server-nodeport
  ports:
  - port: 80
    targetPort: 80
    name: http