grafana:
  enabled: false
  helm:
    valueFiles:
    - .values/grafana.yaml

loki:
  enabled: true
  helm:
    valueFiles:
    - .values/loki.yaml

mimir:
  enabled: false
  helm:
    valueFiles:
    - .values/mimir.yaml

tempo:
  enabled: false
  helm:
    valueFiles:
    - .values/tempo.yaml

grafana-oncall:
  enabled: false
  helm:
    valueFiles:
    - .values/grafana-oncall.yaml

alloy:
  enabled: false
  helm:
    valueFiles:
    - .values/alloy.yaml

serviceMonitor:
  enabled: false

commonConfig:
  replication_factor: 1
