grafana:
  enabled: false
  values:
  - .values/grafana.yaml

loki:
  enabled: true
  values:
  - .values/loki.yaml

mimir:
  enabled: false
  values:
  - .values/mimir.yaml

tempo:
  enabled: false
  values:
  - .values/tempo.yaml

grafana-oncall:
  enabled: false
  values:
  - .values/grafana-oncall.yaml

alloy:
  enabled: false
  values:
  - .values/alloy.yaml

serviceMonitor:
  enabled: false
