grafana:
  enabled: false
  values:
  - ./grafana.yaml

loki:
  enabled: true
  values:
  - ./loki.yaml

mimir:
  enabled: false
  values:
  - ./mimir.yaml

tempo:
  enabled: false
  values:
  - ./tempo.yaml

grafana-oncall:
  enabled: false
  values:
  - ./grafana-oncall.yaml

alloy:
  enabled: false
  values:
  - ./alloy.yaml

serviceMonitor:
  enabled: false
