apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontdoor
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-2
            port:
              number: 80