apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: argo.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            namespace: default
            name: argo-lb
            port:
              number: 80
  - host: test.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            namespace: default
            name: nginx-test-2
            port:
              number: 80