apiVersion: v1
kind: Service
metadata:
  name: lab-ingress
  namespace: ingress-nginx
  annotations:
    metallb.universe.tf/address-pool: primary-pool-ipv4
spec:
  type: LoadBalancer
  selector:
    name: lab-ingress
  ports:
  - port: 80
    targetPort: 80
    name: http
    
